#!/usr/bin/env python3
"""Generate porto_features/matrix/sdk.yaml from @sdk feature scenarios."""

from __future__ import annotations

import re
import sys
from pathlib import Path

try:
    from gherkin.parser import Parser
except ImportError:
    print("❌ Error: gherkin-official package not installed")
    sys.exit(1)

SCOPE_OPERATOR_PREFIX = "operator:"
CONCERN_ALIASES = {
    "delivery_resolution": "resolution",
    "api_comprehensive_testing": "pricing",
}

PRIMARY_COUNTRY_ZONES = {
    "DE": "domestic",
    "FR": "zone_1_eu",
    "UA": "zone_2_europe",
    "US": "world",
    "XX": "invalid",
}

PORTO_ID_RE = re.compile(
    r'(?:the letter porto_id is|porto_id is|with porto_id|porto_id)\s+"([a-z_]+)"',
    re.IGNORECASE,
)
COUNTRY_RE = re.compile(
    r'(?:I want to send a letter to country|destination country|the destination country is)\s+"([A-Z]{2})"',
    re.IGNORECASE,
)
ZONE_ASSERT_RE = re.compile(r'zone with id "([a-z0-9_]+)"', re.IGNORECASE)
REGION_RE = re.compile(r"UA-\d+")

FILE_HEADER = """\
# SDK layer index — pointers to Gherkin only (no duplicated scenario text).
# cell_id: {provider}.{concern}.{slice}.{porto_id}.{zone}
# Generated by scripts/generate_sdk_matrix.py — do not hand-edit refs.

schema_version: 1

sdk_cells:
"""


def _feature_tags(feature: dict) -> set[str]:
    tags: set[str] = set()
    for tag in feature.get("tags", []):
        name = tag.get("name", "")
        if name.startswith("@"):
            tags.add(name[1:])
    return tags


def _iter_scenario_nodes(feature: dict) -> list[dict]:
    nodes: list[dict] = []
    for child in feature.get("children", []):
        if child.get("scenario"):
            nodes.append(child)
        elif child.get("rule"):
            for rule_child in child["rule"].get("children", []):
                if rule_child.get("scenario"):
                    nodes.append(rule_child)
    return nodes


def _scenario_step_text(scenario_obj: dict) -> str:
    lines: list[str] = []
    for step in scenario_obj.get("steps", []):
        text = step.get("text", "")
        if text:
            lines.append(text)
        for row in step.get("argument", {}).get("rows", []):
            for cell in row.get("cells", []):
                value = cell.get("value", "")
                if value:
                    lines.append(value)
    return "\n".join(lines)


def _provider_from_context(rel_path: Path, feature_tags: set[str]) -> str:
    if "core" in feature_tags:
        return "global"
    for tag in feature_tags:
        if tag.startswith(SCOPE_OPERATOR_PREFIX):
            return tag[len(SCOPE_OPERATOR_PREFIX) :]
    parts = rel_path.parts
    if "providers" in parts:
        idx = parts.index("providers")
        if idx + 1 < len(parts):
            return parts[idx + 1]
    return "global"


def _concern_from_path(rel_path: Path) -> str:
    stem = rel_path.stem.replace("-", "_")
    return CONCERN_ALIASES.get(stem, stem)


def _extract_porto_id(text: str) -> str | None:
    match = PORTO_ID_RE.search(text)
    return match.group(1) if match else None


def _extract_country(text: str) -> str | None:
    match = COUNTRY_RE.search(text)
    return match.group(1) if match else None


def _extract_zone(text: str, provider: str, country: str | None) -> str | None:
    region = REGION_RE.search(text)
    if region:
        return region.group(0)

    zone_match = ZONE_ASSERT_RE.search(text)
    if zone_match:
        return zone_match.group(1)

    if country:
        if provider in {"deutschepost", "global"} and country in PRIMARY_COUNTRY_ZONES:
            return PRIMARY_COUNTRY_ZONES[country]
        if provider == "laposte" and country == "FR":
            return "domestic"
        if provider == "swisspost" and country == "CH":
            return "domestic"
        if provider == "ukrposhta" and country == "UA":
            return "domestic"

    if "restricted country" in text.lower():
        return "restricted"
    return None


def _infer_slice(scenario_name: str, text: str, keyword: str) -> str:
    if keyword == "Scenario Outline":
        return "matrix"

    name = scenario_name.lower()
    body = text.lower()

    if "ua-14" in name or "ua-14" in body or "prohibited" in body:
        return "prohibited"
    if any(token in name for token in ("invalid", "reject", "missing", "too heavy", "exceeding")):
        return "invalid_input"
    if "ambiguous" in name or "disambiguation" in name:
        return "disambiguation"
    if any(token in name for token in ("restriction", "sanctions", "restricted country")):
        return "restriction"
    if "warning" in name or "edge case" in name:
        return "scope"
    if "service" in name or "registered" in name or "mark profile" in name:
        return "service_variant"
    if any(
        token in name
        for token in (
            "metadata",
            "registry",
            "list",
            "catalog",
            "manifest",
            "envelope",
            "integrations",
            "access ",
        )
    ):
        return "metadata"
    if "cli" in name or "cli " in body:
        return "metadata"
    if "weight" in name and any(token in name for token in ("boundary", "tier", "maximum")):
        return "weight_boundary"
    if "simulate" in name:
        return "happy"
    return "happy"


def _slug_suffix(name: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_")
    return slug[:32]


def _make_cell_id(
    provider: str,
    concern: str,
    slice_name: str,
    porto_id: str | None,
    zone: str | None,
    scenario_name: str,
    used: set[str],
) -> str:
    parts = [provider, concern, slice_name, porto_id or "null", zone or "null"]
    base = ".".join(parts)
    cell_id = base
    if cell_id in used:
        cell_id = f"{base}.{_slug_suffix(scenario_name)}"
        counter = 2
        while cell_id in used:
            cell_id = f"{base}.{_slug_suffix(scenario_name)}_{counter}"
            counter += 1
    used.add(cell_id)
    return cell_id


def _matrix_ref(rel_path: Path, keyword: str, scenario_name: str) -> str:
    ref_path = rel_path.as_posix()
    if keyword == "Scenario Outline":
        return f"{ref_path}:Scenario Outline:{scenario_name}"
    return f"{ref_path}:Scenario:{scenario_name}"


def _scan_sdk_features(features_dir: Path) -> list[dict]:
    sdk_root = features_dir / "sdk"
    if not sdk_root.is_dir():
        return []

    parser = Parser()
    cells: list[dict] = []
    used_ids: set[str] = set()

    for feature_path in sorted(sdk_root.rglob("*.feature")):
        gherkin_document = parser.parse(feature_path.read_text(encoding="utf-8"))
        feature = gherkin_document.get("feature")
        if not feature:
            continue

        feature_tags = _feature_tags(feature)
        if "sdk" not in feature_tags:
            continue

        rel_path = feature_path.relative_to(features_dir)
        provider = _provider_from_context(rel_path, feature_tags)
        concern = _concern_from_path(rel_path)

        for node in _iter_scenario_nodes(feature):
            scenario_obj = node["scenario"]
            scenario_name = scenario_obj.get("name", "Unnamed")
            keyword = scenario_obj.get("keyword", "Scenario")
            text = _scenario_step_text(scenario_obj)
            porto_id = _extract_porto_id(text)
            country = _extract_country(text)
            zone = _extract_zone(text, provider, country)
            slice_name = _infer_slice(scenario_name, text, keyword)
            cell_id = _make_cell_id(
                provider, concern, slice_name, porto_id, zone, scenario_name, used_ids
            )

            cells.append(
                {
                    "cell_id": cell_id,
                    "provider": provider,
                    "concern": concern,
                    "slice": slice_name,
                    "porto_id": porto_id,
                    "zone": zone,
                    "status": "required",
                    "refs": [_matrix_ref(rel_path, keyword, scenario_name)],
                }
            )

    return cells


def _dump_sdk_yaml(cells: list[dict]) -> str:
    lines = [FILE_HEADER.rstrip("\n")]
    for cell in cells:
        lines.append(f"  - cell_id: {cell['cell_id']}")
        lines.append(f"    provider: {cell['provider']}")
        lines.append(f"    concern: {cell['concern']}")
        lines.append(f"    slice: {cell['slice']}")
        porto_id = cell["porto_id"]
        zone = cell["zone"]
        lines.append(f"    porto_id: {porto_id if porto_id is not None else 'null'}")
        lines.append(f"    zone: {zone if zone is not None else 'null'}")
        lines.append("    status: required")
        lines.append("    refs:")
        for ref in cell["refs"]:
            lines.append(f"      - {ref}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def generate_sdk_matrix(features_dir: Path, output_path: Path) -> int:
    cells = _scan_sdk_features(features_dir)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(_dump_sdk_yaml(cells), encoding="utf-8")
    print(f"✅ Wrote {len(cells)} sdk cells to {output_path.relative_to(output_path.parents[2])}")
    return len(cells)


def main() -> None:
    import argparse

    parser = argparse.ArgumentParser(description="Generate porto_features/matrix/sdk.yaml from @sdk scenarios.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if sdk.yaml is out of date (no write).",
    )
    args = parser.parse_args()

    project_root = Path(__file__).parent.parent
    features_dir = project_root / "porto_features" / "features"
    output_path = project_root / "porto_features" / "matrix" / "sdk.yaml"
    expected = _dump_sdk_yaml(_scan_sdk_features(features_dir))
    if args.check:
        if not output_path.is_file():
            print(f"❌ Missing {output_path.relative_to(project_root)} — run generate_sdk_matrix.py")
            sys.exit(1)
        actual = output_path.read_text(encoding="utf-8")
        if actual != expected:
            print(
                f"❌ {output_path.relative_to(project_root)} is out of date — "
                "run: python scripts/generate_sdk_matrix.py"
            )
            sys.exit(1)
        print(f"✅ sdk.yaml is up to date ({expected.count('cell_id:')} cells)")
        sys.exit(0)

    count = generate_sdk_matrix(features_dir, output_path)
    if count == 0:
        print("❌ No @sdk scenarios found")
        sys.exit(1)
    sys.exit(0)


if __name__ == "__main__":
    main()
